'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.17929
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "My.Settings Auto-Save Functionality"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(ByVal sender As Global.System.Object, ByVal e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("damprover09")>  _
        Public Property UserID() As String
            Get
                Return CType(Me("UserID"),String)
            End Get
            Set
                Me("UserID") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("damprover09")>  _
        Public Property Password() As String
            Get
                Return CType(Me("Password"),String)
            End Get
            Set
                Me("Password") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("damserver")>  _
        Public Property DB_server() As String
            Get
                Return CType(Me("DB_server"),String)
            End Get
            Set
                Me("DB_server") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property PulserASubsystem() As Integer
            Get
                Return CType(Me("PulserASubsystem"),Integer)
            End Get
            Set
                Me("PulserASubsystem") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property PulserBSubsystem() As Integer
            Get
                Return CType(Me("PulserBSubsystem"),Integer)
            End Get
            Set
                Me("PulserBSubsystem") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0, 0")>  _
        Public Property Location() As Global.System.Drawing.Point
            Get
                Return CType(Me("Location"),Global.System.Drawing.Point)
            End Get
            Set
                Me("Location") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("6, 13")>  _
        Public Property Dimensions() As Global.System.Drawing.SizeF
            Get
                Return CType(Me("Dimensions"),Global.System.Drawing.SizeF)
            End Get
            Set
                Me("Dimensions") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property PulserADataFlow() As Integer
            Get
                Return CType(Me("PulserADataFlow"),Integer)
            End Get
            Set
                Me("PulserADataFlow") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property PulserBDataFlow() As Integer
            Get
                Return CType(Me("PulserBDataFlow"),Integer)
            End Get
            Set
                Me("PulserBDataFlow") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("5")>  _
        Public Property PulserOutSubsystem() As Integer
            Get
                Return CType(Me("PulserOutSubsystem"),Integer)
            End Get
            Set
                Me("PulserOutSubsystem") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property PulserOutDataFlow() As Integer
            Get
                Return CType(Me("PulserOutDataFlow"),Integer)
            End Get
            Set
                Me("PulserOutDataFlow") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Auto")>  _
        Public Property LowPressureHighTemp() As String
            Get
                Return CType(Me("LowPressureHighTemp"),String)
            End Get
            Set
                Me("LowPressureHighTemp") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Auto")>  _
        Public Property MidPressureMidTemp() As String
            Get
                Return CType(Me("MidPressureMidTemp"),String)
            End Get
            Set
                Me("MidPressureMidTemp") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Auto")>  _
        Public Property HighPressureLowTemp() As String
            Get
                Return CType(Me("HighPressureLowTemp"),String)
            End Get
            Set
                Me("HighPressureLowTemp") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property ExcelReport() As Boolean
            Get
                Return CType(Me("ExcelReport"),Boolean)
            End Get
            Set
                Me("ExcelReport") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("b38400")>  _
        Public Property TCIBaudRate() As Global.miSerialProtocol.BaudRateEnum
            Get
                Return CType(Me("TCIBaudRate"),Global.miSerialProtocol.BaudRateEnum)
            End Get
            Set
                Me("TCIBaudRate") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("5")>  _
        Public Property TCICommPort() As Integer
            Get
                Return CType(Me("TCICommPort"),Integer)
            End Get
            Set
                Me("TCICommPort") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("33333")>  _
        Public Property TCIAccessCode() As Integer
            Get
                Return CType(Me("TCIAccessCode"),Integer)
            End Get
            Set
                Me("TCIAccessCode") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("35")>  _
        Public Property TempLimit() As String
            Get
                Return CType(Me("TempLimit"),String)
            End Get
            Set
                Me("TempLimit") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("80")>  _
        Public Property PressureLimit() As String
            Get
                Return CType(Me("PressureLimit"),String)
            End Get
            Set
                Me("PressureLimit") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0.8")>  _
        Public Property TempPercentageMax() As Double
            Get
                Return CType(Me("TempPercentageMax"),Double)
            End Get
            Set
                Me("TempPercentageMax") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0.8")>  _
        Public Property PressurePercentageMax() As Double
            Get
                Return CType(Me("PressurePercentageMax"),Double)
            End Get
            Set
                Me("PressurePercentageMax") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property UncVolumeOnly() As Boolean
            Get
                Return CType(Me("UncVolumeOnly"),Boolean)
            End Get
            Set
                Me("UncVolumeOnly") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property ManualPressure() As Boolean
            Get
                Return CType(Me("ManualPressure"),Boolean)
            End Get
            Set
                Me("ManualPressure") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property ManualTemp() As Boolean
            Get
                Return CType(Me("ManualTemp"),Boolean)
            End Get
            Set
                Me("ManualTemp") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property CustomerId() As Integer
            Get
                Return CType(Me("CustomerId"),Integer)
            End Get
            Set
                Me("CustomerId") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("""DT335(00)""")>  _
        Public Property PCIBoardName() As String
            Get
                Return CType(Me("PCIBoardName"),String)
            End Get
            Set
                Me("PCIBoardName") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property USBBoardName() As String
            Get
                Return CType(Me("USBBoardName"),String)
            End Get
            Set
                Me("USBBoardName") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property BoardType() As String
            Get
                Return CType(Me("BoardType"),String)
            End Get
            Set
                Me("BoardType") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("COM1")>  _
        Public Property InstrumentCommPort() As String
            Get
                Return CType(Me("InstrumentCommPort"),String)
            End Get
            Set
                Me("InstrumentCommPort") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("38400")>  _
        Public Property InstrumentBaudRate() As String
            Get
                Return CType(Me("InstrumentBaudRate"),String)
            End Get
            Set
                Me("InstrumentBaudRate") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("33333")>  _
        Public Property InstrumentAccessCode() As String
            Get
                Return CType(Me("InstrumentAccessCode"),String)
            End Get
            Set
                Me("InstrumentAccessCode") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("C:\Mi Testing Files\")>  _
        Public Property ExcelLocation() As String
            Get
                Return CType(Me("ExcelLocation"),String)
            End Get
            Set
                Me("ExcelLocation") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property SetInstrumentDateTime() As Boolean
            Get
                Return CType(Me("SetInstrumentDateTime"),Boolean)
            End Get
            Set
                Me("SetInstrumentDateTime") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("C:\Mi Testing Files\")>  _
        Public Property RotaryMetricExcel() As String
            Get
                Return CType(Me("RotaryMetricExcel"),String)
            End Get
            Set
                Me("RotaryMetricExcel") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("C:\Mi Testing Files\")>  _
        Public Property MechExcel() As String
            Get
                Return CType(Me("MechExcel"),String)
            End Get
            Set
                Me("MechExcel") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("C:\Mi Testing Files\")>  _
        Public Property MechMetricExcel() As String
            Get
                Return CType(Me("MechMetricExcel"),String)
            End Get
            Set
                Me("MechMetricExcel") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("COM2")>  _
        Public Property TachCommPort() As String
            Get
                Return CType(Me("TachCommPort"),String)
            End Get
            Set
                Me("TachCommPort") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1.0")>  _
        Public Property PressureTolerance() As String
            Get
                Return CType(Me("PressureTolerance"),String)
            End Get
            Set
                Me("PressureTolerance") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1.0")>  _
        Public Property TemperatureTolerance() As String
            Get
                Return CType(Me("TemperatureTolerance"),String)
            End Get
            Set
                Me("TemperatureTolerance") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0.3")>  _
        Public Property SuperTolerance() As String
            Get
                Return CType(Me("SuperTolerance"),String)
            End Get
            Set
                Me("SuperTolerance") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0.1")>  _
        Public Property UncVolumeTolerance() As String
            Get
                Return CType(Me("UncVolumeTolerance"),String)
            End Get
            Set
                Me("UncVolumeTolerance") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1.0")>  _
        Public Property CorVolumeTolerance() As String
            Get
                Return CType(Me("CorVolumeTolerance"),String)
            End Get
            Set
                Me("CorVolumeTolerance") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("dam_prover_test")>  _
        Public Property DB() As String
            Get
                Return CType(Me("DB"),String)
            End Get
            Set
                Me("DB") = value
            End Set
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("server=damserver;user id=root;password=!crw@work;persist security info=True;datab"& _ 
            "ase=dam_prover_test")>  _
        Public ReadOnly Property dam_proverConnectionString() As String
            Get
                Return CType(Me("dam_proverConnectionString"),String)
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\crwall-01\Company\Inspection Certificates\MASTER MI testing files\CRWIC-trial.r"& _ 
            "pt")>  _
        Public Property ICLocation() As String
            Get
                Return CType(Me("ICLocation"),String)
            End Get
            Set
                Me("ICLocation") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("2.0.0.0")>  _
        Public Property version() As String
            Get
                Return CType(Me("version"),String)
            End Get
            Set
                Me("version") = value
            End Set
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.DAM_Prover.My.MySettings
            Get
                Return Global.DAM_Prover.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
