'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class customer
    Public Property customer_id As Integer
    Public Property name As String
    Public Property address As String
    Public Property postal_code As String
    Public Property reg_number As Nullable(Of Integer)

    Public Overridable Property write_items As ICollection(Of write_items) = New HashSet(Of write_items)

End Class
