'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class inspection_cert
    Public Property inspection_id As Integer
    Public Property [date] As Date
    Public Property customer_id As Nullable(Of Integer)
    Public Property comments As String
    Public Property insp_type As String
    Public Property event_log As Byte

End Class
