'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class instr
    Public Property customer_id As Nullable(Of Integer)
    Public Property serial_number As String
    Public Property [date] As Nullable(Of Date)
    Public Property approver As String
    Public Property instr_type_id As Nullable(Of Integer)
    Public Property inspection_id As Nullable(Of Integer)
    Public Property meter_index_id As Nullable(Of Integer)
    Public Property pass As Nullable(Of Byte)
    Public Property data As String
    Public Property instr_id As System.Guid

End Class
