'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class instr_info
    Public Property instr_id As Integer
    Public Property item_number As Nullable(Of Integer)
    Public Property item_value As String

    Public Overridable Property instr As instr

End Class
