'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class item_units
    Public Property item_number As Integer
    Public Property value As Nullable(Of Integer)
    Public Property unit_desc As String
    Public Property unit_value As Nullable(Of Double)

End Class
