'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class pressure
    Public Property instr_id As Integer
    Public Property p_level As Integer
    Public Property gauge_pressure As Nullable(Of Double)
    Public Property atm_pressure As Nullable(Of Double)
    Public Property evc_pressure As Nullable(Of Double)
    Public Property evc_pfactor As Nullable(Of Double)
    Public Property evc_unsqr_super As Nullable(Of Double)

    Public Overridable Property instr As instr

End Class
