'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class DAMProverEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=DAMProverEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Property customers() As DbSet(Of customer)
    Public Property equipements() As DbSet(Of equipement)
    Public Property inspection_cert() As DbSet(Of inspection_cert)
    Public Property item_units() As DbSet(Of item_units)
    Public Property items() As DbSet(Of item)
    Public Property meter_index() As DbSet(Of meter_index)
    Public Property pressures() As DbSet(Of pressure)
    Public Property temperatures() As DbSet(Of temperature)
    Public Property volume_test() As DbSet(Of volume_test)
    Public Property write_items() As DbSet(Of write_items)
    Public Property instrs() As DbSet(Of instr)

End Class
