'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class temperature
    Public Property instr_id As Integer
    Public Property t_level As Integer
    Public Property gauge_temp As Nullable(Of Double)
    Public Property evc_temp As Nullable(Of Double)
    Public Property evc_factor As Nullable(Of Double)

    Public Overridable Property instr As instr

End Class
