'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class volume_test
    Public Property instr_id As Integer
    Public Property pulse_input As Nullable(Of Double)
    Public Property pulser_a As Nullable(Of Double)
    Public Property pulser_b As Nullable(Of Double)
    Public Property end_uncor As Nullable(Of Double)
    Public Property end_cor As Nullable(Of Double)
    Public Property energy As Nullable(Of Double)
    Public Property mech_read As Nullable(Of Double)

End Class
